# Generated by Django 5.0 on 2023-12-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('año_nacimiento', models.IntegerField()),
                ('partidos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Jugadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('año_nacimiento', models.IntegerField()),
                ('partidos_jugados', models.IntegerField()),
                ('goles', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Partidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
                ('torneo', models.CharField(max_length=50)),
                ('fecha1', models.DateField()),
                ('fecha', models.CharField(max_length=50)),
                ('rival', models.CharField(max_length=50)),
                ('rdo1', models.IntegerField()),
                ('rdo2', models.IntegerField()),
                ('resultado', models.CharField(max_length=50)),
                ('goles', models.CharField(max_length=50)),
                ('condicion', models.CharField(max_length=50)),
                ('estadio', models.CharField(max_length=50)),
                ('localidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rivales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('localidad', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('partidos_disputados', models.IntegerField()),
                ('partidos_ganados', models.IntegerField()),
                ('partidos_empatados', models.IntegerField()),
                ('partidos_perdidos', models.IntegerField()),
            ],
        ),
    ]
